### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by searchivarius**

### CODE REVIEW

**Comment by benfred** [comment]
I'l fix the python unittest for osx there

**Comment by searchivarius** [comment]
Let me look at this, I think it's a minor issue.

**Comment by benfred** [comment]
Think the error is with importing being different on python3. this patch should fix i think

```
diff --git a/python_bindings/tests/sparse_bench.py b/python_bindings/tests/sparse_bench.py
index dfa369a..46cc30d 100755
--- a/python_bindings/tests/sparse_bench.py
+++ b/python_bindings/tests/sparse_bench.py
@@ -6,7 +6,7 @@ import os
 import time
 import numpy as np
 import nmslib
-from common import *
+from .common import *
 
 
 def bench_sparse_vector(batch=True):
diff --git a/python_bindings/tests/test_nmslib.py b/python_bindings/tests/test_nmslib.py
index 6acfc52..d406ed3 100755
--- a/python_bindings/tests/test_nmslib.py
+++ b/python_bindings/tests/test_nmslib.py
@@ -6,7 +6,7 @@ import os
 import time
 import numpy as np
 import nmslib
-from common import *
+from .common import *
 
 MAX_PRINT_QTY=5
```

**Comment by searchivarius** [comment]
But it works on my laptop with Python 3. Shouldn't I simply add:
```
common>=0.1.2
```
to the requirements.txt?

**Comment by benfred** [comment]
Its trying to import the 'python_bindings/tests/common.py' file (has some timing utils). 

I'm not sure why this broke (and it used to work for me too =(.

**Comment by benfred** [comment]
fwiw - with that patch it works on my mac with python2 + 3 right now, but without it it only works with python2.

**Comment by benfred** [comment]
hmm, though that breaks running these things without going things like 'python2 -m tests.test_nmslib'  which seems verbose. Maybe the solution here is to move test_nmslib and sparse_bench into an integration_tests folder that setup.py doesn't include in the test suite?

**Comment by searchivarius** [comment]
This is an interesting question. We also have another integration test, however, it's not stable. One needs to replace all random generation code with a seeded deterministic version to make it really useful.

**Pull request closed without merging**
