### PR TITLE
additional information on README

### PR DESCRIPTION
**Pull request by eracle**

### CODE REVIEW

**Comment by searchivarius** [comment]
Thank you! Was it really useful? This undocumented method was created to overcome some issues with SW-graph indexing. However, afterwards, the indexing speed was improved. It is even faster with HNSW. So, I decided to keep this one undocumented. We also have some new clustering methods. However, they didn't prove very useful on interesting workloads, so I have not documented them either. Perhaps, someday.

**Comment by eracle** [comment]
You welcome,
In reality, right now I'm only using the small_world_rand method (I'm new
on this repo).
All begun when I was wondering on which other methods offered the storage
feature, so I searched into the "similarity_search/src/method"  folder for
the key-words: SaveIndex e LoadIndex and I found those four files.

Right now, I'm trying to create an index with all the italian words (the
ubuntu dic, made by 116878 words) and searching with leven distance for fun
on it.
I noted that the resulting file of the index I created is 25MB, so I
checked the file storage format and it seems to be the adjacency matrix
(uncompressed: It affects a lot performances), so I searched on the net
about graph storage libraries and I found that one
<http://cnets.indiana.edu/groups/nan/webgraph/>, maybe it could help,
because I'm not a pro on c++ (but who knows, maybe I can try).



2016-05-23 21:12 GMT+02:00 Leonid Boytsov <notifications@github.com>:

> Thank you! Was it really useful? This undocumented method was created to
> overcome some issues with SW-graph indexing. However, afterwards, the
> indexing speed was improved. It is even faster with HNSW. So, I decided to
> keep this one undocumented. We also have some new clustering methods.
> However, they didn't prove very useful on interesting workloads, so I have
> not documented them either. Perhaps, someday.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/searchivarius/nmslib/pull/96#issuecomment-221063184>
>



-- 
Antonio Ercole De Luca
Linkedin:
http://www.linkedin.com/pub/antonio-ercole-de-luca/1b/340/197
Github:
https://github.com/eracle


To Iterate is Human, recurse Divine.
James O. Coplien.


To be or not to be is true.
G. Boole

**Comment by searchivarius** [comment]
For small objects, the whole framework isn't very efficient. In particular, for strings. We have a method (binarized permutations) that has a much smaller memory footprint, yet, similar performance on the string data. It doesn't support serialization yet.

In general, support for string spaces is currently very weak. Should we decide to do more work on string spaces, we would need to implement specialized methods for strings. Sometimes, these will work much faster. In particular, for a simple Levenshtein distance, on your data set of 100K words, answering queries would take dozens of microseconds. For longer string pieces, the situation may be different, but, again, one may need to compare to specialized methods based on uni and bidirectional suffix trees/arrays.

**Comment by eracle** [comment]
Yes, thank you very much, but the string case is not my use case.
I was searching for general methods for storage indexes on disk.
I will continue my experiments, thank you very much for your avalaibility

**Pull request closed without merging**
