### PR TITLE
Allow Python Handling of log messages

### PR DESCRIPTION
**Pull request by benfred**
This change lets Python LogHandlers handle the log messages
produced by nmslib.

This lets python control the behaviour
of the log messages at run time, meaning that the loglevel
can be adjusted and that the output of the messages can
be handled any python loghandler.

This basically involves transforming the existing logger class into
an abstract base, and then creating a python version that adapts
the nmslib log system to the python version.

### CODE REVIEW

**Comment by searchivarius** [comment]
Looks good, thanks a lot! but I would need a bit more time to test it.

**Comment by searchivarius** [comment]
This is a lot of changes. I will also try to run a couple of tests. We will need to be more consistent in logging in the future.

**Comment by mattiasarro** [comment]
So should the following disable [INFO] log messages?

```
import logging

logging.basicConfig(level=logging.WARNING)
logging.getLogger('nmslib').setLevel(logging.WARNING)

import nmslib
```

I'm still seeing various messages, e.g.
`2017-11-14 16:26:51 methodfactory.h:49 (Register) [INFO] Registering at the factory, method: ...`
 `2017-11-14 16:30:50 hnsw.cc:178 (CreateIndex) [INFO] ...`

**Comment by mattiasarro** [comment]
So should the following suppress [INFO] log messages?

```
import logging

logging.basicConfig(level=logging.ERROR)
logging.getLogger('nmslib').setLevel(logging.ERROR)

import nmslib
```

I'm still seeing a lot of INFO messages, though, e.g.

```
2017-11-14 16:43:41 methodfactory.h:49 (Register) [INFO] Registering at the factory, method: vptree distance type: INT
2017-11-14 16:43:03 hnsw.cc:337 (CreateIndex) [INFO] Thus using an optimised function for base 4
```

**Comment by benfred** [comment]
@mattiasarro This code isn't in  master yet (nor in pypi) - did you install from develop branch here?

**Comment by mattiasarro** [comment]
Oh, right. I was using a pip installation. Thanks!

**Comment by phdowling** [comment]
Is this in master yet? I just upgraded with pip but am still seeing these logs

**Comment by benfred** [comment]
@phdowling This is in master, you shouldn't see these logs anymore (unless you are logging DEBUG statements).

It's possible you are still running an old version - what does this print out: ```python -c 'import nmslib; print(nmslib.__version__)'``` ?

**Comment by searchivarius** [comment]
@phdowling it's in the master.

**Comment by phdowling** [comment]
Hey guys, sorry about that - I had updated nmslib in a terminal that had an open SSH session to another machine. All is good

**Pull request merged**
