### PR TITLE
Use pybind11 for python bindings

### PR DESCRIPTION
**Pull request by benfred**
Pybind11 removes a lot of the boilerplate with creating python bindings for c++ projects.
This code switches the NMSLIB bindings to using pybind11, fixing a couple minor
problems:

 * Works with Python2/3
 * Works on Linux / OSX / Windows
 * Add docstrings for each function, and sensible default parameters
 * More pythonic API: exposes an Index object with methods on it
 * No need to call nmslib.freeIndex anymore (memory gets GC'ed with python object)

Fixes this issue https://github.com/searchivarius/nmslib/issues/109

### CODE REVIEW

**Comment by searchivarius** [comment]
Hi @benfred this looks great except one thing. I am not so sure about using openmp because of MacOS. We have an implementation that does rely on OpenMP, but I really want to get rid of OpenMP in it as well. What do you think?

**Comment by searchivarius** [comment]
PS: also don't worry about the ANN-benchmark. We will change it to work with new bindings.

**Comment by benfred** [comment]
Makes sense - I pushed a version there that doesn't need openmp here https://github.com/searchivarius/nmslib/pull/195/commits/3bbb9f0aff7dddd94df5dff91add148f43d11581

It will be slightly faster to go with something like [std::atomic::fetch_add](http://en.cppreference.com/w/cpp/atomic/atomic/fetch_add) instead of using a mutex to lock - but I thought I'd keep it consistent with other code here

**Comment by searchivarius** [comment]
Great, it's a good observation that we don't need the queue in this simple case. The atomics would be even better.

**Comment by bileg** [comment]
Hi @benfred. It looks really awesome. Thank you!

**Pull request merged**
