### PR TITLE
Fix col-major array bug in Python bindings

### LINKED ISSUE #230: Python bindings produce incorrect results for arrays in Fortran order
I realized that I'm getting very weird results when I read numpy arrays from csv files via the `as_matrix()` function of Pandas dataframes. Then, I found out that it's because of the order the matrices are stored in memory:

```python
import nmslib as nn
import numpy as np

np.random.seed(42)
X = np.random.rand(1000, 50)

index = nn.init(method='vptree', space='l2')
index.addDataPointBatch(X)
index.createIndex()
print(index.knnQueryBatch(X, k=5)[0][0])

X2 = np.asfortranarray(X)
print(np.allclose(X, X2))

print(index.knnQueryBatch(X2, k=5)[0][0])
print(index.knnQuery(X2[0], k=5)[0])  # knnQuery works well

X3 = np.ascontiguousarray(X2)
print(index.knnQueryBatch(X3, k=5)[0][0])
```

Produces following output:

```
[  0  13 694 168 895]
True
[247 784  11 243 986]
[  0  13 694 168 895]
[  0  13 694 168 895]
```

As users may not really know about the order of the matrix, `nmslib` bindings must call `np.ascontiguousarray()` explicitly in `addDataPointBatch` and `knnQueryBatch ` without assuming that matrices are in C order.

### PR DESCRIPTION
**Pull request by gokceneraslan**
Fixes #230.

### CODE REVIEW

**Comment by gokceneraslan** [comment]
The test to reproduce the bug (in #230) is as follows:

```python
import nmslib as nn
import numpy as np

np.random.seed(42)
X = np.random.rand(1000, 50)

index = nn.init(method='vptree', space='l2')
index.addDataPointBatch(X)
index.createIndex()
print(index.knnQueryBatch(X, k=5)[0][0])

X2 = np.asfortranarray(X)
print(np.allclose(X, X2))

print(index.knnQueryBatch(X2, k=5)[0][0])
print(index.knnQuery(X2[0], k=5)[0])  # knnQuery works well

X3 = np.ascontiguousarray(X2)
print(index.knnQueryBatch(X3, k=5)[0][0])

```

and here is the correct output with this PR:

```
[  0  13 694 168 895]
True
[  0  13 694 168 895]
[  0  13 694 168 895]
[  0  13 694 168 895]
```

**Comment by searchivarius** [comment]
Great, many thanks! One little question: I think I am getting the correct output even using the old code. Why is that?

**Comment by gokceneraslan** [comment]
Oh, that's weird, that shouldn't happen actually :) Can you try this one as well:

```python
import nmslib as nn
import numpy as np

np.random.seed(42)
X = np.random.rand(1000, 50)

index = nn.init(method='vptree', space='l2')
index.addDataPointBatch(X)
index.createIndex()
res = np.vstack([x[0] for x in index.knnQueryBatch(X, k=5)])

X2 = np.asfortranarray(X.copy())
res2 = np.vstack([x[0] for x in index.knnQueryBatch(X2, k=5)])

assert np.all(res == res2), 'Col-major is not working'
print('ok')
```

**Comment by searchivarius** [comment]
It says (Python 3):
``
  File "test_arr1.py", line 15, in <module>
    assert np.all(res == res2), 'Col-major is not working'
AssertionError: Col-major is not working
```
Does it make more sense?

**Comment by gokceneraslan** [comment]
We compare the 5-NN indices of two queries that are essentially the same, so they should match but they don't. When you apply the commit in this PR, it should print "ok" without any exception.

**Comment by searchivarius** [comment]
@gokceneraslan great many thanks! I think it should all work now: tests are fine and your example did fail before your patch.

**Comment by gokceneraslan** [comment]
Thank you.

**Pull request merged**
