### PR TITLE
Add basic python documentation

### PR DESCRIPTION
**Pull request by benfred**
Using sphinx and autodoc, expose the built in docstrings as html pages.

The generated documenation can be viewed here:
https://benfred.github.io/nmslib/index.html

This documentation can be generated by going 'make html' in the python_bindings/doc folder 
(requires ```pip install sphinx sphinx_rtd_theme``` to run first, and the nmslib python bindings need to be
installed for the default python as well).

### CODE REVIEW

**Comment by searchivarius** [comment]
Great, thanks a lot. Are there instructions how to create a github.io site?

**Comment by benfred** [comment]
If you create a 'gh-pages' branch in github for this repo - I can submit a PR against that branch with the generated html pages (that will show up here http://searchivarius.github.io/nmslib/). Longer term we can set it up so that the travis build automatically pushes the generated HTML documentation to this branch to keep it in sync.

I also want to flesh out the documentation a little bit here - and I see some formatting errors in the docstrings that I also want to clean up.

**Comment by searchivarius** [comment]
Hi @benfred but regarding a longer term solutions, where to start with this, i.e., docs etc?

**Comment by benfred** [comment]
Documentation on getting started with githubpages is here : https://pages.github.com/ . github will basically host HTML files on your gh-pages branch at searchivarius.github.io/nmslib/ .

All I did to host the generated html pages was to copy them over to the root of my nmslib project and commit them (as well as delete all the source code): so the branch looks like https://github.com/benfred/nmslib/tree/gh-pages

I know some projects that automate this step, by having travis push the generated html pages to their gh-pages on every build. as an example  https://github.com/maciejkula/spotlight does this. 

There are some guides online on how to set this up. For instance: https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

Alternatively, we could use something like readthedocs to do this. I use it for this project here : implicit.readthedocs.io

**Comment by searchivarius** [comment]
@benfred many thanks, I will look into this when I have a bit more time. This is great, I appreciate your help very much.

**Comment by searchivarius** [comment]
Hi @benfred I tried to create a web-site, but it is crippled https://searchivarius.github.io/nmslib/
My understanding of this is as follows: files from the _static sub-folders are not published for some reason. However:

1. They are in the repo https://github.com/searchivarius/nmslib/tree/gh-pages
2. Yet compare https://benfred.github.io/nmslib/_static/jquery.js vs https://searchivarius.github.io/nmslib/_static/jquery.js

Same thing happens to other CSS or JS files. Do you have any idea why this can be the case? Totally beats me. 
Thank you!

**Comment by benfred** [comment]
So - you need to have a file called '.nojekyll' in the repo like https://github.com/benfred/nmslib/blob/gh-pages/.nojekyll  . If you add an empty file there it *should* all work.

However, I hoped this would have have been created automatically - I added the 'githubpages' extension to sphinx thats supposed to do this https://github.com/searchivarius/nmslib/blob/develop/python_bindings/docs/conf.py#L34
I'm away right now still, but can take a look next week at why this isn't working

**Comment by searchivarius** [comment]
Great, many thanks! This wasn't obvious by a cursory look through the docs. BTW, I decided not to have a separate branch: it's much more convenient to serve stuff from the masters/doc folder.

**Pull request merged**
