### PR TITLE
add WITHOUT_TESTS, fix IdType bugs

### PR DESCRIPTION
**Pull request by cdump**
1. Allow to build without tests via WITHOUT_TESTS cmake
2. Fix bugs in types. Before this commit it was impossible to compile project without fatal errors if you change IdType typedef in IdType.h file

### CODE REVIEW

**Comment by searchivarius** [comment]
Hi Maxim,

IdType issue is by design. If you change IdType you have to change IdTypeUnsign. We are not going to use 64-bit ids right away, it's not so easy to do, b/c of the alignment problems.

**Comment by cdump** [comment]
Hi.
Of course I mean IdTypeUnsign too. I'm talking about this change:
```-typedef int32_t  IdType;
-typedef uint32_t IdTypeUnsign;
+typedef int64_t  IdType;
+typedef uint64_t IdTypeUnsign;
```
And yes, alignment is the second step to use 64bit

**Comment by searchivarius** [comment]
Do we really need 64-bit IDs right away? If you introduce 64-bit IDs, you basically need either change the layout of Object, or get rid of dist_t=double, which is not a bad idea anywyas. Otherwise, we will have problems like this one: https://github.com/searchivarius/nmslib/issues/9

Yes, we mostly use our own SIMD implementation, but something may sleep through the cracks, so I basically want to be sure we are compliant in the sense that float* pointers are aligned on 4 bytes and double* pointers are aligned on 8 bytes. Or, we remove all the doubles. Again, this is not such a bad idea, because they are not used. So, maybe it's time to remove them.

**Comment by cdump** [comment]
I need 64 bit Id's in my project, I'm using some hacks now to not to deal with alignment issues (hack object.h to alignment of data not changed).
I think this commit may become first part of using 64bit sometimes in future, anyway I think it's a bug to use IdType for label variable for example (which is fixed in this commit).
So, it's not for 64-bit ID's "right now", but it fixes some related bugs

**Comment by searchivarius** [comment]
Ok, then 
1) I would encourage you to remove all the code related to the label variable. Again, similar to double it wasn't useful at all. Whoever needs to do classification can store id-label relationship somewhere else.
2) What about Python bindings and the query server? Does 64-bit id break them?

**Comment by searchivarius** [comment]
BTW, if we remove label, we would get an 8-byte alignment, so we wan't have problem with doubles.

**Comment by searchivarius** [comment]
Ohh, sorry, I got confused a bit. Ok, Label has to go, but no rush.

Well, ok. I used IdTypeUnsign to make the count of the data set size to be in sync with the id size. However, this, probably, not necessary. 
1. 64-bit id doesn't mean we will deal with > 2B entries on the same machine.
2. But if we do, many more changes will be necessary anyway. So, let it be simply (32-bit) unsigned for now.

**Comment by cdump** [comment]
@searchivarius I need 64-bit id not to store >2^31 entries, I just have 64bit id somewhere and don't want to to store nmslib-id32 <-> my-id64 table.

**Comment by searchivarius** [comment]
Yes, I eventually figured this out, no problem.

**Pull request merged**
