### PR TITLE
Add GetSize() to Index

### PR DESCRIPTION
**Pull request by 8W9aG**
* Adds a protected variable called data_ to reduce
boilerplate
* Implements GetSize in the Index class

### CODE REVIEW

**Comment by searchivarius** [comment]
@8W9aG there's still a small issue related to a recent modification of HNSW, but I will fix it after the merge. Thank you!

**Comment by 8W9aG** [comment]
@searchivarius what is the branching strategy in regards to develop, master and cutting releases in this project?

**Comment by searchivarius** [comment]
@8W9aG there's not much of a strategy, but I am trying to keep master stable. So at the very least, I encourage branching from dev.

**Comment by searchivarius** [comment]
Ok, there we go. I think this should compile on Linux/Mac, but I still have to fix this Python issue on Windows.

**Comment by searchivarius** [comment]
@benfred gee I forgot to test with EXTRAS, many thanks!

**Pull request merged**
