### PR TITLE
Fix python3 unittests

### PR DESCRIPTION
**Pull request by benfred**
'python3 setup.py test' was complaining about failing to import the 'common'
module. Fix by moving the integration tests to a separate folder

All the tests should pass with these changes: https://travis-ci.org/benfred/nmslib

### CODE REVIEW

**Comment by searchivarius** [comment]
Great this seems to work. I will merge the recent changes into master and create a pipy package!

**Comment by benfred** [comment]
awesome!

**Comment by searchivarius** [comment]
I can't agree more!!! It's in the master now and the badge: build passes is there. A couple of questions:
1) I want to add a PyPI badge, is this a good website to create a Badge?
2) what is necessary to activate the automatic build on Windows?
Thank you!

**Comment by benfred** [comment]
1) I'm not sure about the best place for pypi badges - but I've seen people use shields.io (like using https://img.shields.io/pypi/v/nmslib.svg for the image - will have the pypi version once you push it).

2) The windows build wasn't working - I've fixed with that last PR there https://github.com/searchivarius/nmslib/pull/208 . You can enable the build here https://ci.appveyor.com for your project - steps should be similar to travis . The output will look like https://ci.appveyor.com/project/benfred/nmslib .

**Comment by searchivarius** [comment]
Great, I think I have tamed the Windows build and the badges. One need to set the build to x64 though. Will try to get a pypi bad as well!

**Comment by benfred** [comment]
Nice! Thanks for getting the pypi version up and going. I tested out the pypi version by going 'pip install nmslib' on both an ubuntu and osx machine - and it worked seamlessly in both cases.

I've made some minor updates to the README to reflect installing from pypi as the best option for python. Also I tweaked the badges so clicking on the pypi badge takes you to the page on pypi and clicking on the appveyor badge does the same: https://github.com/searchivarius/nmslib/pull/210

**Pull request merged**
